package sys.model;
// Generated 24/11/2016 10:10:07 AM by Hibernate Tools 4.3.1



/**
 * Tbempleado generated by hbm2java
 */
public class Tbempleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombres;
     private String apellidos;
     private String direccion;
     private int idPais;
     private int idDepartamento;
     private int idMunicipio;
     private String codigoArea;
     private String telefono;

    public Tbempleado() {
    }

	
    public Tbempleado(String nombres, String apellidos, String direccion, int idPais, int idDepartamento, int idMunicipio) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.direccion = direccion;
        this.idPais = idPais;
        this.idDepartamento = idDepartamento;
        this.idMunicipio = idMunicipio;
    }
    public Tbempleado(String nombres, String apellidos, String direccion, int idPais, int idDepartamento, int idMunicipio, String codigoArea, String telefono) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.idPais = idPais;
       this.idDepartamento = idDepartamento;
       this.idMunicipio = idMunicipio;
       this.codigoArea = codigoArea;
       this.telefono = telefono;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


