package sys.model;
// Generated 24/11/2016 10:10:07 AM by Hibernate Tools 4.3.1



/**
 * Tbmunicipio generated by hbm2java
 */
public class Tbmunicipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private Tbdepartamento tbdepartamento;
     private String nombreMunicipio;

    public Tbmunicipio() {
    }

    public Tbmunicipio(Tbdepartamento tbdepartamento, String nombreMunicipio) {
       this.tbdepartamento = tbdepartamento;
       this.nombreMunicipio = nombreMunicipio;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Tbdepartamento getTbdepartamento() {
        return this.tbdepartamento;
    }
    
    public void setTbdepartamento(Tbdepartamento tbdepartamento) {
        this.tbdepartamento = tbdepartamento;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }




}


