package sys.model;
// Generated 10-21-2015 08:14:45 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbmunicipio generated by hbm2java
 */
public class Tbmunicipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private Tbdepartamento tbdepartamento;
     private String nombreMunicipio;
     private Set<Tbempleado> tbempleados = new HashSet<Tbempleado>(0);

    public Tbmunicipio() {
    }

	
    public Tbmunicipio(Tbdepartamento tbdepartamento, String nombreMunicipio) {
        this.tbdepartamento = tbdepartamento;
        this.nombreMunicipio = nombreMunicipio;
    }
    public Tbmunicipio(Tbdepartamento tbdepartamento, String nombreMunicipio, Set<Tbempleado> tbempleados) {
       this.tbdepartamento = tbdepartamento;
       this.nombreMunicipio = nombreMunicipio;
       this.tbempleados = tbempleados;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Tbdepartamento getTbdepartamento() {
        return this.tbdepartamento;
    }
    
    public void setTbdepartamento(Tbdepartamento tbdepartamento) {
        this.tbdepartamento = tbdepartamento;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }
    public Set<Tbempleado> getTbempleados() {
        return this.tbempleados;
    }
    
    public void setTbempleados(Set<Tbempleado> tbempleados) {
        this.tbempleados = tbempleados;
    }




}


