package sys.model;
// Generated 24/11/2016 10:10:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbpais generated by hbm2java
 */
public class Tbpais  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;
     private Set<Tbdepartamento> tbdepartamentos = new HashSet<Tbdepartamento>(0);

    public Tbpais() {
    }

	
    public Tbpais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Tbpais(String nombrePais, Set<Tbdepartamento> tbdepartamentos) {
       this.nombrePais = nombrePais;
       this.tbdepartamentos = tbdepartamentos;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Tbdepartamento> getTbdepartamentos() {
        return this.tbdepartamentos;
    }
    
    public void setTbdepartamentos(Set<Tbdepartamento> tbdepartamentos) {
        this.tbdepartamentos = tbdepartamentos;
    }




}


